#!/bin/bash
set -e

###############################################################################
# Fixel-based analysis (FBA): FOD estimation and study-specific template
#
# This script follows the MRtrix3 fixel-based analysis workflow:
# https://mrtrix.readthedocs.io/en/latest/fixel_based_analysis/
# mt_fibre_density_cross-section.html
#
# The input DWI images were generated by:
#   01_dwi_preproc_adni.sh
#
# cp -v <data_path>/<subject_id>_<session>/brain/dwi_preprocessed.mif
#   <data_path>/subjects/<subject_id>_<session>/dwi_denoised_unringed_preproc.mif
#
# Note:
#   The filename "dwi_denoised_unringed_preproc.mif" is retained from the
#   original analysis workflow. This file contains the complete preprocessing
#   output generated by 01_dwi_preproc_adni.sh.
#
# Main steps:
#   1. Estimate subject-specific WM/GM/CSF response functions
#   2. Generate group-average tissue response functions
#   3. Upsample DWI images to 1.3-mm isotropic resolution
#   4. Generate brain masks
#   5. Estimate multi-tissue FODs using MSMT-CSD
#   6. Perform multi-tissue intensity normalization
#   7. Generate a study-specific unbiased FOD template
#   8. Register subject FODs to the study-specific template
#   9. Transform subject masks to template space
#  10. Generate the group template mask
#
# Important outputs:
#   template/wmfod_template.mif
#   subjects/<subject>/subject2template_warp.mif
#   subjects/<subject>/template2subject_warp.mif
#   template/template_mask.mif
#
# The template and nonlinear transformations generated here are subsequently
# used for template-based visual pathway tractography and subject-level
# diffusion metric extraction.
###############################################################################


# -----------------------------------------------------------------------------
# Set working directory
# -----------------------------------------------------------------------------

data_path="$PWD"

subjects_dir="${data_path}/subjects"
template_dir="${data_path}/template"

cd "${subjects_dir}"


###############################################################################
# Step 1. Estimate subject-specific tissue response functions
#
###############################################################################

echo "Estimating subject-specific tissue response functions..."

for_each * : dwi2response dhollander \
    IN/dwi_denoised_unringed_preproc.mif \
    IN/response_wm.txt \
    IN/response_gm.txt \
    IN/response_csf.txt


###############################################################################
# Step 2. Generate group-average response functions
#
###############################################################################

echo "Generating group-average tissue response functions..."

responsemean */response_wm.txt \
    "${data_path}/group_average_response_wm.txt"

responsemean */response_gm.txt \
    "${data_path}/group_average_response_gm.txt"

responsemean */response_csf.txt \
    "${data_path}/group_average_response_csf.txt"


###############################################################################
# Step 3. Upsample DWI images to 1.3-mm isotropic resolution
#
###############################################################################

echo "Upsampling DWI images to 1.3-mm isotropic resolution..."

for_each * : mrgrid \
    IN/dwi_denoised_unringed_preproc.mif \
    regrid \
    -vox 1.3 \
    IN/dwi_denoised_unringed_preproc_unbiased_upsampled.mif


###############################################################################
# Step 4. Generate brain masks for the upsampled DWI images
#
###############################################################################

echo "Generating brain masks..."

for_each * : dwi2mask \
    IN/dwi_denoised_unringed_preproc_unbiased_upsampled.mif \
    IN/dwi_mask_upsampled.mif


###############################################################################
# Step 5. Multi-tissue constrained spherical deconvolution (MSMT-CSD)
#
###############################################################################

echo "Estimating WM, GM, and CSF tissue components..."

for_each * : dwi2fod msmt_csd \
    IN/dwi_denoised_unringed_preproc_unbiased_upsampled.mif \
    ../group_average_response_wm.txt IN/wmfod.mif \
    ../group_average_response_gm.txt IN/gm.mif \
    ../group_average_response_csf.txt IN/csf.mif \
    -mask IN/dwi_mask_upsampled.mif


###############################################################################
# Step 6. Multi-tissue intensity normalization
#
###############################################################################

echo "Performing multi-tissue intensity normalization..."

for_each * : mtnormalise \
    IN/wmfod.mif IN/wmfod_norm.mif \
    IN/gm.mif IN/gm_norm.mif \
    IN/csf.mif IN/csf_norm.mif \
    -mask IN/dwi_mask_upsampled.mif


###############################################################################
# Step 7. Prepare inputs for study-specific FOD template generation
#
# The study-specific template was generated from a balanced subset of
# 30 participants randomly selected from the study cohort:
# 10 cognitively normal controls (NC), 10 participants with mild cognitive
# impairment (MCI), and 10 participants with Alzheimer's disease (AD).
#
# The selected subject IDs are listed in:
#   template_list
###############################################################################
echo "Preparing FOD template inputs..."

mkdir -p "${template_dir}/fod_input"
mkdir -p "${template_dir}/mask_input"

while read -r subj; do
    ln -sr \
        "${subjects_dir}/${subj}/wmfod_norm.mif" \
        "${template_dir}/fod_input/${subj}.mif"

    ln -sr \
        "${subjects_dir}/${subj}/dwi_mask_upsampled.mif" \
        "${template_dir}/mask_input/${subj}.mif"

done < "${data_path}/template_list"


###############################################################################
# Step 8. Generate study-specific unbiased FOD template
#
###############################################################################

echo "Generating study-specific unbiased FOD template..."

population_template \
    "${template_dir}/fod_input" \
    -mask_dir "${template_dir}/mask_input" \
    "${template_dir}/wmfod_template.mif" \
    -voxel_size 1.3


###############################################################################
# Step 9. Register each subject FOD image to the study-specific FOD template
#
# Outputs:
#   subject2template_warp.mif
#   template2subject_warp.mif
#
# template2subject_warp.mif is later used to transform the template-defined
# visual pathway masks back to each subject's diffusion space.
###############################################################################

echo "Registering individual FOD images to the study-specific template..."

for_each * : mrregister \
    IN/wmfod_norm.mif \
    -mask1 IN/dwi_mask_upsampled.mif \
    ../template/wmfod_template.mif \
    -nl_warp \
    IN/subject2template_warp.mif \
    IN/template2subject_warp.mif


###############################################################################
# Step 10. Transform individual brain masks to template space
#
###############################################################################

echo "Transforming individual brain masks to template space..."

for_each * : mrtransform \
    IN/dwi_mask_upsampled.mif \
    -warp IN/subject2template_warp.mif \
    -interp nearest \
    -datatype bit \
    IN/dwi_mask_in_template_space.mif


###############################################################################
# Step 11. Generate study-specific template mask
#
###############################################################################

echo "Generating study-specific template mask..."

mrmath \
    */dwi_mask_in_template_space.mif \
    min \
    "${template_dir}/template_mask.mif" \
    -datatype bit


###############################################################################
# Step 12. Generate a study-specific FA template using the same template cohort
#
# The dwinormalise group workflow was run using the same subjects selected
# for generation of the study-specific FOD template (template_list).
#
# The resulting fa_template.mif was subsequently used as an anatomical
# reference for registration of the HCP-1065 FA template and optic-radiation
# atlas masks to the study-specific template space.
#
# Note:
# Multi-tissue intensity normalization for FOD estimation was performed
# separately using mtnormalise.
###############################################################################

echo "Generating study-specific FA template..."

mkdir -p "${data_path}/dwinormalise/dwi_input"
mkdir -p "${data_path}/dwinormalise/mask_input"
mkdir -p "${data_path}/dwinormalise/dwi_output"

while read -r subj; do
    ln -sr \
        "${subjects_dir}/${subj}/dwi_denoised_unringed_preproc.mif" \
        "${data_path}/dwinormalise/dwi_input/${subj}.mif"

    ln -sr \
        "${subjects_dir}/${subj}/dwi_mask_upsampled.mif" \
        "${data_path}/dwinormalise/mask_input/${subj}.mif"
done < "${data_path}/template_list"

dwinormalise group \
    "${data_path}/dwinormalise/dwi_input" \
    "${data_path}/dwinormalise/mask_input" \
    "${data_path}/dwinormalise/dwi_output" \
    "${data_path}/dwinormalise/fa_template.mif" \
    "${data_path}/dwinormalise/fa_template_wm_mask.mif"


echo "=============================================================="
echo "FBA template generation completed."
echo
echo "Main outputs:"
echo "  ${template_dir}/wmfod_template.mif"
echo "  ${template_dir}/template_mask.mif"
echo "  ${subjects_dir}/<subject>/subject2template_warp.mif"
echo "  ${subjects_dir}/<subject>/template2subject_warp.mif"
echo "=============================================================="

